baseURL = '/'
languageCode = 'en-us'
title = 'The Night Coder Blog'
theme = 'hermit-v2'

[author]
  name = "Buran"
  about = "about"

[markup]
  [markup.highlight]
  style = 'nord'

[params]

  [[params.socialLinks]]
    name = "github"
    url = "https://github.com/1buran/"
  [[params.socialLinks]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/buran-py/"

[menu]
  [[menu.main]]
    name = "Posts"
    url = "posts/"
    weight = 10
  [[menu.main]]
    name = "About"
    url = "about/"
    weight = 20